apiVersion: apps/v1
kind: Deployment
metadata:
  name: interacle_py
spec:
  selector:
    matchLabels:
      app: interacle_py
  replicas: 1
  template:
    metadata:
      labels:
        app: interacle_py
    spec:
      containers:
      - name: interacle_py
        image: docker.io/<your_hub.docker>/<repo>:latest
        env:
        - name: LD_LIBRARY_PATH
          value: oracle
        - name: PYTHON_USERNAME
          value: SYS
        - name: PYTHON_PASSWORD
          value: Oradoc_db1
        - name: PYTHON_CONNECTSTRING
          value: localhost/ORCLCDB
        - name: HOST
          value: localhost
        - name: PORT
          value: 1521
        - name: SID
          value: ORCLCDB
        ports:
        - containerPort: 5000